//Storing catalog in seperate file from Server.js

const catalog = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Book",
    isbn: "123456789",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    category: "Book",
    isbn: "987654321",
  },
  {
    id: 3,
    title: "The Science of Climate Change",
    author: "John Doe",
    category: "Paper",
    isbn: "555555555",
  },
  {
    id: 4,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Book",
    isbn: "111222333",
  },
  {
    id: 5,
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    category: "Book",
    isbn: "444555666",
  },
  {
    id: 6,
    title: "The Art of War",
    author: "Sun Tzu",
    category: "Book",
    isbn: "777888999",
  },
  {
    id: 7,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Book",
    isbn: "666777888",
  },
  {
    id: 8,
    title: "The Quantum Theory of Fields",
    author: "Steven Weinberg",
    category: "Paper",
    isbn: "999000111",
  },
  {
    id: 9,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Book",
    isbn: "222333444",
  },
  {
    id: 10,
    title: "The Origin of Species",
    author: "Charles Darwin",
    category: "Book",
    isbn: "888999000",
  },
  {
    id: 11,
    title: "Advanced Machine Learning",
    author: "Andrew Ng",
    category: "Paper",
    isbn: "112233445",
  },
  {
    id: 12,
    title: "The History of Art",
    author: "E.H. Gombrich",
    category: "Book",
    isbn: "223344556",
  },
  {
    id: 13,
    title: "The Theory of Relativity",
    author: "Albert Einstein",
    category: "Paper",
    isbn: "334455667",
  },
  {
    id: 14,
    title: "War and Peace",
    author: "Leo Tolstoy",
    category: "Book",
    isbn: "556677889",
  },
  {
    id: 15,
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    category: "Book",
    isbn: "145678952",
  },
  {
    id: 16,
    title: "How to be Batman",
    author: "Muhammad Arsalan Saeed",
    category: "Paper",
    isbn: "7894561230",
  },
  {
    id: 17,
    title: "How to be Spider-Man",
    author: "Muhammad Arsalan Saeed",
    category: "Paper",
    isbn: "017258369",
  },
  {
    id: 18,
    title: "Batman Spotted in Gotham",
    author: "Muhammad Arsalan Saeed",
    category: "News",
    isbn: "789489122",
  },
  {
    id: 19,
    title: "Spider-Man Spotted swinging in NYC",
    author: "Muhammad Arsalan Saeed",
    category: "News",
    isbn: "899815156",
  },
];

module.exports = catalog;
